[package]
name = "identicon-rs"
version = "0.2.0"
authors = ["Nia Watts <niawatts95@gmail.com>"]
edition = "2018"
description = """
identicon-rs is a library built around custom generation of identicon images.

# Example:
```rust
use identicon_rs;

fn main() {
    let fluffy_samurai = "fluffy-samurai";
    let test_string = "identicon_rs";
    identicon_rs::save_scaled_image(fluffy_samurai, "output_1.png", 500);
    identicon_rs::save_scaled_image(test_string, "output_2.png", 500);

    identicon_rs::save_bordered_image(fluffy_samurai, "output_1_bordered.png", 500, 50);
    identicon_rs::save_bordered_image(test_string, "output_2_bordered.png", 500, 50);
}
```
"""
documentation = "https://docs.rs/identicon-rs"
homepage = "https://github.com/fluffy-samurai/identicon-rs"
repository = "https://github.com/fluffy-samurai/identicon-rs"
license = "MIT"

[dependencies]
image = "0.21.0"
# num-complex = "0.2.1"
sha2 = "0.8.0"
palette = "0.4.1"
